variable  "ami" {}
variable "instance_type" {}
variable "count" {}
variable "Env" {}
variable "Dept" {}
variable "Created_by" {}
variable "key_name" {}
variable "appname" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "DBname" {}